version: '2.22'

services:
  nginx:
    build:
      context: ./nginx
    ports:
      - "443:443"
#      - "80:80"
    depends_on:
      - apache

  apache:
    build:
      context: ./apache
    ports:
      - "8443:80"
